name: 'Puah Image to ECR'
description: 'Push a local image to the ECR registry provided by the Developer Portal'
author: 'Keboola'
inputs: 
  vendor:
    description: 'Application vendor (e.g. keboola)'
    required: true
  app_id:
    description: 'Application ID (e.g. keboola.ex-db-mysql)'
    required: true
  username:
    description: 'Developer portal Service user name (e.g. keboola+my_app_deploy_user'
    required: true
  password:
    description: 'Developer portal Service user password'
    required: true
  tag:
    description: 'GitHub tag reference (e.g. refs/tags/1.0.0)'
    required: true
  source_image:
    description: 'Name of the image to push (e.g. my-application)'
    required: true
  push_latest:
    description: 'If true, also push to the "latest" tag'
    required: false
    default: false
  image_name_suffix:
    description: 'Image name suffix'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.vendor }}
    - ${{ inputs.app_id }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.tag }}
    - ${{ inputs.source_image }}
    - ${{ inputs.push_latest }}
    - ${{ inputs.image_name_suffix }}
